services:
  caddy:
    image: caddy:2.11.4-alpine
    container_name: caddy
    restart: unless-stopped

    ports:
      - "100.110.175.52:80:80"

    volumes:
      - ./caddy:/etc/caddy:ro
      - caddy-data:/data
      - caddy-config:/config

    depends_on:
      - grafana
      - copyparty

  coredns:
    image: coredns/coredns:1.14.7
    container_name: coredns
    restart: unless-stopped

    command:
      - "-conf"
      - "/etc/coredns/Corefile"

    ports:
      - target: 53
        host_ip: "100.110.175.52"
        published: "53"
        protocol: udp
      - target: 53
        host_ip: "100.110.175.52"
        published: "53"
        protocol: tcp

    volumes:
      - ./coredns:/etc/coredns:ro

  copyparty:
    image: copyparty/iv:1.20.21
    container_name: copyparty
    restart: unless-stopped
    user: "1000:1000"

    volumes:
      - /srv/copyparty:/w
      - copyparty-state:/cfg
      - ./copyparty/copyparty.conf:/cfg/copyparty.conf:ro
      - ./copyparty/accounts.conf:/cfg/zz-accounts.conf:ro

    stop_grace_period: 15s

    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q 127.0.0.1:3923/?reset=/._"]
      interval: 1m
      timeout: 2s
      retries: 5
      start_period: 15s

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    group_add:
      - "1000"

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus:/etc/prometheus:ro
      - ./prometheus/copyparty_metrics_password:/run/secrets/copyparty_metrics_password:ro
      - prometheus-data:/prometheus

    extra_hosts:
      - "host.docker.internal:host-gateway"

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=30d"
      - "--storage.tsdb.retention.size=1GB"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped

    ports:
      - "3000:3000"

    volumes:
      - grafana-data:/var/lib/grafana

      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro

    depends_on:
      - prometheus

volumes:
  caddy-data:
  caddy-config:
  prometheus-data:
  grafana-data:
  copyparty-state:
