global:
  evaluation_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10m
    static_configs:
      - targets:
          - "prometheus:9090"

  - job_name: "machines"
    scrape_interval: 1m
    static_configs:
      - targets:
          - "host.docker.internal:9100"
        labels:
          host: "ocelot"
      - targets:
          - "kokod:9100"
        labels:
          host: "kokod"
