[global]
  ansi
  http-only
  usernames
  ah-alg: argon2
  ah-salt: de4531319c1576b99debc702

  e2dsa
  e2ts
  hist: /cfg/hists/

  name: ocelot files
  site: http://files.home.tverghis.space/
  no-robots

  xff-hdr: x-forwarded-for
  xff-src: lan
  rproxy: 1

  stats
  stats-u: prometheus
  nos-dup

  vc-url: https://api.copyparty.eu/advisories

[/]
  /w
  accs:
    rwmda: tarun
    rwmd: emma
